/******************************************************************************
|
| Copyright (c) 2018 streamingnology Inc (https://github.com/streamingnology)
|
| This file is part of HTTP Server
|
| Permission is hereby granted, free of charge, to any person obtaining a copy
| of this software and associated documentation files (the "Software"), to deal
| in the Software without restriction, including without limitation the rights
| to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
| copies of the Software, and to permit persons to whom the Software is
| furnished to do so, subject to the following conditions:
|
| The above copyright notice and this permission notice shall be included in all
| opies or substantial portions of the Software.
|
| THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
| MPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
| FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
| AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
| LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
| OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
| OFTWARE.
 ******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_streamingnology_httpserver_HTTPServer */

#ifndef _Included_com_streamingnology_httpserver_HTTPServer
#define _Included_com_streamingnology_httpserver_HTTPServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_streamingnology_httpserver_HTTPServer
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_streamingnology_httpserver_HTTPServer_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_streamingnology_httpserver_HTTPServer
 * Method:    nativeOpen
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_streamingnology_httpserver_HTTPServer_nativeOpen
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_streamingnology_httpserver_HTTPServer
 * Method:    nativeStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_streamingnology_httpserver_HTTPServer_nativeStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_streamingnology_httpserver_HTTPServer
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_streamingnology_httpserver_HTTPServer_nativeStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_streamingnology_httpserver_HTTPServer
 * Method:    nativeGetErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_streamingnology_httpserver_HTTPServer_nativeGetErrorMessage
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
